version: '3'
services:
    apache:
        build: .docker/apache
        container_name: adsmurai_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/adsmurai
        depends_on:
          - php

    mysql:
        image: mysql
        container_name: adsmurai_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: adsmurai
            MYSQL_USER: adsmurai
            MYSQL_PASSWORD: adsmurai

    php:
        build: .docker/php
        container_name: adsmurai_php
        volumes:
          - .:/home/wwwroot/adsmurai
        depends_on:
          - mysql